#pragma once

#define SCREEN_MODE_PAL 0
#define SCREEN_MODE_NTSC 1

#define SCREEN_WIDTH_COMMON 320
#define SCREEN_HEIGHT_PAL 256
#define SCREEN_HEIGHT_NTSC 240

#define OT_LENGTH 1
#define PACKETMAX 300